language: node_js
node_js:
  - '8.16.1'
  - '10'
  - '12'
cache: npm

env:
  - PACKAGE: '@-k/eslint-plugin'

jobs:
  include:
    - install: npm install
      script: npm run lerna --scope $PACKAGE test
