language: node_js
cache: npm

stages:
  - test

anchors:
  - &test-eslint-plugin
    stage: test
    name: eslint-plugin
    install: npm install
    script: npm run lerna -- --scope=@-k/eslint-plugin run test


jobs:
  include:
    - <<: *test-eslint-plugin
      node_js: '8.16.1'
    - <<: *test-eslint-plugin
      node_js: '10'
    - <<: *test-eslint-plugin
      node_js: '12'
