language: node_js
node_js:
  - '8.16.1'
  - '10'
  - '12'
cache: npm

stages:
  - test

jobs:
  include:
    - stage: test
      name: eslint-plugin
      install: npm install
      script: npm run lerna -- --scope=@-k/eslint-plugin run test
